<?php

//application details
$apps[$x]['name'] = "Phone";
$apps[$x]['uuid'] = "7051a36f-06f0-4489-a2fb-12b120e209b6";
$apps[$x]['category'] = "";
$apps[$x]['subcategory'] = "";
$apps[$x]['version'] = "1.1";
$apps[$x]['license'] = "Mozilla Public License 1.1";
$apps[$x]['url'] = "http://www.fusionpbx.com";
$apps[$x]['description']['en-us'] = "A browser-based softphone for FusionPBX.";
$apps[$x]['description']['en-gb'] = "A browser-based softphone for FusionPBX";
$apps[$x]['description']['ar-eg'] = "";
$apps[$x]['description']['de-at'] = "";
$apps[$x]['description']['de-ch'] = "";
$apps[$x]['description']['de-de'] = "";
$apps[$x]['description']['el-gr'] = "";
$apps[$x]['description']['es-cl'] = "";
$apps[$x]['description']['es-mx'] = "";
$apps[$x]['description']['fr-ca'] = "";
$apps[$x]['description']['fr-fr'] = "";
$apps[$x]['description']['he-il'] = "";
$apps[$x]['description']['it-it'] = "";
$apps[$x]['description']['nl-nl'] = "";
$apps[$x]['description']['pl-pl'] = "";
$apps[$x]['description']['pt-br'] = "";
$apps[$x]['description']['pt-pt'] = "";
$apps[$x]['description']['ro-ro'] = "";
$apps[$x]['description']['ru-ru'] = "";
$apps[$x]['description']['sv-se'] = "";
$apps[$x]['description']['uk-ua'] = "";

//default settings
$y=0;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d04a022a-f917-4195-b631-80e02c2f1422";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_enabled";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e313c253-351c-4772-8269-6b5eeac296ef";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_domain";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2ce8d190-8063-4e8a-a069-04a1da78097b";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_path";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "/app/contacts/contacts.php";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "cca31993-0315-4c48-95aa-41b3de4a63df";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_parameter";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "search";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ce660e19-20fb-4381-b4b2-ae73e152cbf8";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_target";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "_blank";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "option: _blank, _self";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "be029498-0c88-42ee-a5a2-38965cdd4a16";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_width";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3fe06c0c-aefe-49ac-8730-564a90b2783c";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "phone";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "search_height";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "";

//permission details
$y=0;
$apps[$x]['permissions'][$y]['name'] = "phone_view";
$apps[$x]['permissions'][$y]['menu']['uuid'] = "dff62ee9-f59e-4686-bc57-a4819ea303bf";
$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
$apps[$x]['permissions'][$y]['groups'][] = "admin";
$y++;

